# Generated by Django 5.2.5 on 2025-08-31 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_number', models.CharField(max_length=20, verbose_name='Space Number')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('gps_coordinates', models.CharField(blank=True, help_text='Comma-separated latitude and longitude.', max_length=100, verbose_name='GPS Coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Zone Name')),
                ('gps_coordinates', models.CharField(blank=True, help_text='Comma-separated latitude and longitude.', max_length=100, verbose_name='GPS Coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(blank=True, max_length=255, unique=True, verbose_name='QR Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_allocations', to='events.internationalmatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_allocations', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='parking.parkingspace')),
            ],
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='parking.parkingzone'),
        ),
        migrations.AlterUniqueTogether(
            name='parkingspace',
            unique_together={('zone', 'space_number')},
        ),
    ]
