# Generated by Django 4.2.16 on 2025-06-09 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysicalCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        help_text="Same as digital card number", max_length=12
                    ),
                ),
                (
                    "print_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Print"),
                            ("PRINTED", "Printed"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("ordered_date", models.DateTimeField(auto_now_add=True)),
                ("printed_date", models.DateTimeField(blank=True, null=True)),
                ("shipped_date", models.DateTimeField(blank=True, null=True)),
                ("delivered_date", models.DateTimeField(blank=True, null=True)),
                (
                    "shipping_address",
                    models.TextField(help_text="Address for card delivery"),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, help_text="Shipping tracking number", max_length=50
                    ),
                ),
                (
                    "card_type",
                    models.CharField(default="PHYSICAL", editable=False, max_length=10),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="physical_card",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Physical Card",
                "verbose_name_plural": "Physical Cards",
                "ordering": ["-ordered_date"],
            },
        ),
        migrations.CreateModel(
            name="DigitalCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        help_text="Unique card number (auto-generated)",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "card_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for QR code security",
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("EXPIRED", "Expired"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("issued_date", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_date",
                    models.DateField(
                        help_text="Card expiry date (syncs with membership expiry)"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "qr_code_data",
                    models.TextField(
                        blank=True, help_text="Encrypted data for QR code"
                    ),
                ),
                (
                    "qr_code_version",
                    models.IntegerField(
                        default=1, help_text="QR code version for security updates"
                    ),
                ),
                (
                    "card_type",
                    models.CharField(default="DIGITAL", editable=False, max_length=10),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_card",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Digital Card",
                "verbose_name_plural": "Digital Cards",
                "ordering": ["-issued_date"],
            },
        ),
    ]
