# Generated by Django 5.2.3 on 2025-06-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership_cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitalcard",
            name="card_number",
            field=models.CharField(
                help_text="Unique card number (auto-generated)",
                max_length=16,
                unique=True,
            ),
        ),
    ]
