# Generated by Django 5.2.5 on 2025-08-29 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership_cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalcard",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Card design template to use instead of the default.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="membership_cards.physicalcardtemplate",
            ),
        ),
    ]
