# Generated by Django 5.2.3 on 2025-06-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership_cards", "0002_alter_digitalcard_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitalcard",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("SUSPENDED", "Suspended"),
                    ("EXPIRED", "Expired"),
                    ("REVOKED", "Revoked"),
                    ("YELLOW CARD", "Yellow Card"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
