# Generated by Django 4.2.16 on 2025-06-09 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("membership_cards", "0002_add_qr_image_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysicalCardTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Template name", max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard Member Card"),
                            ("OFFICIAL", "Official/Admin Card"),
                            ("PLAYER", "Player Card"),
                            ("COACH", "Coach Card"),
                            ("REFEREE", "Referee Card"),
                            ("EXECUTIVE", "Executive Card"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                (
                    "card_front_image",
                    models.ImageField(
                        help_text="Front side template image",
                        upload_to="card_templates/front/",
                    ),
                ),
                (
                    "card_back_image",
                    models.ImageField(
                        blank=True,
                        help_text="Back side template image (optional)",
                        null=True,
                        upload_to="card_templates/back/",
                    ),
                ),
                ("name_position_x", models.IntegerField(default=50)),
                ("name_position_y", models.IntegerField(default=100)),
                ("photo_position_x", models.IntegerField(default=20)),
                ("photo_position_y", models.IntegerField(default=20)),
                ("qr_position_x", models.IntegerField(default=200)),
                ("qr_position_y", models.IntegerField(default=150)),
                (
                    "card_width",
                    models.IntegerField(
                        default=856, help_text="Card width in pixels (300 DPI)"
                    ),
                ),
                (
                    "card_height",
                    models.IntegerField(
                        default=540, help_text="Card height in pixels (300 DPI)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Physical Card Template",
                "verbose_name_plural": "Physical Card Templates",
            },
        ),
        migrations.AddField(
            model_name="physicalcard",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Card design template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="membership_cards.physicalcardtemplate",
            ),
        ),
    ]
