# Generated by Django 5.2.5 on 2025-08-29 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_tickets",
                to="membership.invoice",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="events.internationalmatch",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.seatmap"
            ),
        ),
    ]
