# Generated by Django 5.2.5 on 2025-08-29 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        ("membership", "0001_initial"),
        ("supporters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="supporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="supporters.supporterprofile",
            ),
        ),
        migrations.AddField(
            model_name="ticketgroup",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_groups",
                to="membership.invoice",
            ),
        ),
        migrations.AddField(
            model_name="ticketgroup",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_groups",
                to="events.internationalmatch",
            ),
        ),
        migrations.AddField(
            model_name="ticketgroup",
            name="primary_contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="supporters.supporterprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seatmap",
            unique_together={("stadium", "section", "row", "seat_number")},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("match", "seat")},
        ),
    ]
