version: '3.9'
services:
  web:
    build: .
    command: ["/code/entrypoint.sh"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: safa_db
      POSTGRES_USER: neetiesister
      POSTGRES_PASSWORD: neetie12345
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
