# Generated by Django 5.2.5 on 2025-08-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporterprofile',
            name='safa_id',
            field=models.CharField(blank=True, help_text='Unique SAFA ID for Supporter', max_length=5, null=True, unique=True),
        ),
    ]
