# Generated by Django 5.2.3 on 2025-06-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supporters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supporterprofile",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("PREMIUM", "Premium Supporter"),
                    ("VIP", "VIP Supporter"),
                    ("FAMILY_BASIC", "Family Basic Package"),
                    ("FAMILY_PREMIUM", "Family Premium Package"),
                    ("FAMILY_VIP", "Family VIP Package"),
                ],
                default="PREMIUM",
                max_length=20,
            ),
        ),
    ]
