# Generated by Django 5.2.3 on 2025-06-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supporters", "0002_alter_supporterprofile_membership_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="supporterprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Latitude coordinate",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supporterprofile",
            name="location_accuracy",
            field=models.FloatField(
                blank=True, help_text="Location accuracy in meters", null=True
            ),
        ),
        migrations.AddField(
            model_name="supporterprofile",
            name="location_city",
            field=models.CharField(
                blank=True, help_text="City from geolocation", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="supporterprofile",
            name="location_country",
            field=models.CharField(
                blank=True, help_text="Country from geolocation", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="supporterprofile",
            name="location_province",
            field=models.CharField(
                blank=True, help_text="Province from geolocation", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="supporterprofile",
            name="location_timestamp",
            field=models.DateTimeField(
                blank=True, help_text="When location was captured", null=True
            ),
        ),
        migrations.AddField(
            model_name="supporterprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Longitude coordinate",
                max_digits=11,
                null=True,
            ),
        ),
    ]
