# Generated by Django 5.2 on 2025-05-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0015_membership_payment_confirmed_membership_payment_date"),
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transfer",
            options={
                "ordering": ["-request_date"],
                "permissions": [
                    ("can_initiate_transfer", "Can initiate player transfers"),
                    ("can_approve_transfer", "Can approve player transfers"),
                    ("can_reject_transfer", "Can reject player transfers"),
                    ("can_view_transfer", "Can view player transfers"),
                ],
                "verbose_name": "Player Transfer",
                "verbose_name_plural": "Player Transfers",
            },
        ),
        migrations.AddField(
            model_name="club",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="membership_clubs",
                to="geography.province",
                verbose_name="Province",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="membership_clubs",
                to="geography.region",
                verbose_name="Region",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN_SYSTEM", "System Administrator"),
                    ("ADMIN_COUNTRY", "Country Administrator"),
                    ("ADMIN_FEDERATION", "Federation Administrator"),
                    ("ADMIN_PROVINCE", "Provincial Administrator"),
                    ("ADMIN_REGION", "Regional Administrator"),
                    ("ADMIN_LOCAL_FED", "Local Federation Administrator"),
                    ("CLUB_ADMIN", "Club Administrator"),
                    ("STAFF", "Staff Member"),
                    ("PLAYER", "Player"),
                    ("COACH", "Coach"),
                    ("OFFICIAL", "Official"),
                    ("SUPPORTER", "Supporter"),
                ],
                default="PLAYER",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
