# Generated by Django 5.2.2 on 2025-06-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0003_alter_club_safa_id"),
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubWithSafaID",
            fields=[],
            options={
                "verbose_name": "Club with SAFA ID",
                "verbose_name_plural": "Clubs with SAFA ID",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("geography.club",),
        ),
    ]
