# Generated by Django 5.2.3 on 2025-06-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="passport_number",
            field=models.CharField(
                blank=True,
                help_text="Passport number for non-citizens",
                max_length=25,
                null=True,
                verbose_name="Passport Number",
            ),
        ),
    ]
