# Generated by Django 4.2.16 on 2025-06-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="transfer_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Transfer fee amount in ZAR (South African Rand)",
                max_digits=10,
                verbose_name="Transfer Fee (ZAR)",
            ),
        ),
    ]
