# Generated by Django 5.2.3 on 2025-06-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_member_passport_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="id_document",
            field=models.FileField(
                blank=True,
                help_text="Upload a scan/photo of the ID or passport",
                null=True,
                upload_to="documents/member_documents/",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="id_document_type",
            field=models.CharField(
                choices=[("ID", "SA ID"), ("PP", "Passport")],
                default="ID",
                help_text="Type of identification document (SA ID or Passport)",
                max_length=2,
            ),
        ),
    ]
