# Generated by Django 5.2.3 on 2025-06-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0003_member_id_document_member_id_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Whether the player has been approved by an admin",
                verbose_name="Approved",
            ),
        ),
    ]
