# Generated by Django 5.2.5 on 2025-08-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0003_safainvoicesequence_safainvoicetemplate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Postal Code"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="state",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="State/Province"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="street_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Street Address"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="suburb",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Suburb"
            ),
        ),
    ]
