# Generated by Django 5.2.3 on 2025-06-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0004_player_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="has_sa_passport",
            field=models.BooleanField(
                default=False,
                help_text="Whether the SA citizen player also has a valid SA passport for international travel",
                verbose_name="Has SA Passport",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="sa_passport_number",
            field=models.CharField(
                blank=True,
                help_text="South African passport number for citizens (for international travel)",
                max_length=25,
                null=True,
                verbose_name="SA Passport Number",
            ),
        ),
    ]
