# Generated by Django 5.2.5 on 2025-08-28 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_member_city_alter_member_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Issue Date'),
        ),
    ]
