# Generated by Django 5.2.3 on 2025-06-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0005_player_has_sa_passport_player_sa_passport_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="sa_passport_document",
            field=models.FileField(
                blank=True,
                help_text="Upload a copy of the SA passport",
                null=True,
                upload_to="sa_passport_documents/",
                verbose_name="SA Passport Document",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="sa_passport_expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Expiry date of the South African passport",
                null=True,
                verbose_name="SA Passport Expiry Date",
            ),
        ),
    ]
