# Generated by Django 5.2.5 on 2025-08-29 04:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_alter_invoice_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date'),
        ),
    ]
