# Generated by Django 5.2.3 on 2025-06-20 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("membership", "0006_player_sa_passport_document_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Official",
            fields=[
                (
                    "member_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="membership.member",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the official has been approved by an admin",
                        verbose_name="Approved",
                    ),
                ),
                (
                    "certification_number",
                    models.CharField(
                        blank=True,
                        help_text="Certification or license number if applicable",
                        max_length=50,
                        null=True,
                        verbose_name="Certification Number",
                    ),
                ),
                (
                    "certification_document",
                    models.FileField(
                        blank=True,
                        help_text="Upload proof of certification or qualification",
                        null=True,
                        upload_to="certification_documents/",
                        verbose_name="Certification Document",
                    ),
                ),
                (
                    "certification_expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Expiry date of the certification or license",
                        null=True,
                        verbose_name="Certification Expiry Date",
                    ),
                ),
                (
                    "referee_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOCAL", "Local"),
                            ("REGIONAL", "Regional"),
                            ("PROVINCIAL", "Provincial"),
                            ("NATIONAL", "National"),
                            ("INTERNATIONAL", "International"),
                        ],
                        help_text="Level of referee qualification if applicable",
                        max_length=20,
                        null=True,
                        verbose_name="Referee Level",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        help_text="Official's position or role in the club/association",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="officials",
                        to="accounts.position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Official",
                "verbose_name_plural": "Officials",
            },
            bases=("membership.member",),
        ),
    ]
