# Generated by Django 5.2.5 on 2025-08-29 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_alter_invoice_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='member',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='member',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='member',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='suburb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Suburb'),
        ),
    ]
