# Generated by Django 5.2.5 on 2025-08-31 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0004_geographyupdatelog'),
        ('membership', '0007_alter_invoice_issue_date_alter_member_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='current_club',
            field=models.ForeignKey(blank=True, help_text='Current club this member belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_members', to='geography.club'),
        ),
    ]
