# Generated by Django 5.2.3 on 2025-06-20 09:46

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0004_club_affiliation_fees_paid"),
        ("membership", "0007_official"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="official",
            field=models.ForeignKey(
                blank=True,
                help_text="Official this invoice is for (if official registration)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="membership.official",
            ),
        ),
        migrations.AddField(
            model_name="official",
            name="associations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Referee or coaching associations this official belongs to",
                related_name="member_officials",
                to="geography.association",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="player",
            field=models.ForeignKey(
                blank=True,
                help_text="Player this invoice is for (if player registration)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="membership.player",
            ),
        ),
        migrations.CreateModel(
            name="OfficialCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "certification_type",
                    models.CharField(
                        choices=[
                            ("REFEREE", "Referee Certification"),
                            ("COACH", "Coaching Certification"),
                            ("ADMIN", "Administrative Certification"),
                            ("OTHER", "Other Certification"),
                        ],
                        help_text="Type of certification",
                        max_length=20,
                        verbose_name="Certification Type",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local"),
                            ("REGIONAL", "Regional"),
                            ("PROVINCIAL", "Provincial"),
                            ("NATIONAL", "National"),
                            ("INTERNATIONAL", "International"),
                        ],
                        help_text="Level or grade of the certification",
                        max_length=20,
                        verbose_name="Level",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the specific certification or qualification",
                        max_length=100,
                        verbose_name="Certification Name",
                    ),
                ),
                (
                    "issuing_body",
                    models.CharField(
                        help_text="Organization that issued this certification",
                        max_length=100,
                        verbose_name="Issuing Organization",
                    ),
                ),
                (
                    "certification_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for this certification",
                        max_length=50,
                        null=True,
                        verbose_name="Certification Number",
                    ),
                ),
                (
                    "obtained_date",
                    models.DateField(
                        help_text="When the certification was first obtained",
                        verbose_name="Date Obtained",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="When the certification expires (if applicable)",
                        null=True,
                        verbose_name="Expiry Date",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="Upload proof of certification",
                        null=True,
                        upload_to="certification_documents/history/",
                        verbose_name="Certificate Document",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional information about this certification",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this certification has been verified by an administrator",
                        verbose_name="Verified",
                    ),
                ),
                (
                    "official",
                    models.ForeignKey(
                        help_text="The official who holds this certification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="membership.official",
                    ),
                ),
            ],
            options={
                "verbose_name": "Official Certification",
                "verbose_name_plural": "Official Certifications",
                "ordering": ["-obtained_date"],
            },
        ),
    ]
