# Generated by Django 5.2.5 on 2025-09-01 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_alter_member_current_club'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_submission_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when proof of payment was submitted', null=True, verbose_name='Payment Submission Date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted the proof of payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_invoice_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='proof_of_payment',
            field=models.FileField(blank=True, help_text='Upload proof of payment document or receipt', null=True, upload_to='payment_proofs/%Y/%m/', verbose_name='Proof of Payment'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Payment'), ('PENDING_REVIEW', 'Pending Review (Proof Submitted)'), ('PAID', 'Fully Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('PARTIALLY_PAID', 'Partially Paid')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, choices=[('PLAYER', 'Player'), ('OFFICIAL', 'Official'), ('ADMIN', 'Administrator'), ('SUPPORTER', 'Supporter')], max_length=20, null=True, verbose_name='Member Role'),
        ),
    ]
