# Generated by Django 5.2.3 on 2025-06-20 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0004_club_affiliation_fees_paid"),
        ("membership", "0008_invoice_official_official_associations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="association",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="geography.association",
            ),
        ),
    ]
