# Generated by Django 5.2.3 on 2025-06-21 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_create_referee_association_org_type"),
        ("membership", "0009_invoice_association"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="organization_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary organization type this member belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.organizationtype",
            ),
        ),
    ]
