# Generated by Django 5.2.5 on 2025-09-01 21:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_invoice_payment_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Unit Price (Excl. VAT)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('EFT', 'Electronic Funds Transfer'), ('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Payment'), ('MOBILE', 'Mobile Payment'), ('OTHER', 'Other'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=50, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Price (Excl. VAT)'),
        ),
    ]
