# Generated by Django 5.2.5 on 2025-09-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_invoiceitem_unit_price_alter_invoice_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='from_address',
            field=models.TextField(blank=True, verbose_name='From Address'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='from_name',
            field=models.CharField(default='SAFA Connect', max_length=200, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='to_address',
            field=models.TextField(blank=True, verbose_name='To Address'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='to_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='To'),
        ),
    ]
