# Generated by Django 4.2.23 on 2025-07-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0027_juniormember_remove_member_club_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='has_sa_passport',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sa_passport_document',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sa_passport_expiry_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sa_passport_number',
        ),
        migrations.AddField(
            model_name='member',
            name='has_sa_passport',
            field=models.BooleanField(default=False, help_text='Whether the SA citizen member also has a valid SA passport for international travel', verbose_name='Has SA Passport'),
        ),
        migrations.AddField(
            model_name='member',
            name='sa_passport_document',
            field=models.FileField(blank=True, help_text='Upload a copy of the SA passport', null=True, upload_to='sa_passport_documents/', verbose_name='SA Passport Document'),
        ),
        migrations.AddField(
            model_name='member',
            name='sa_passport_expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date of the South African passport', null=True, verbose_name='SA Passport Expiry Date'),
        ),
        migrations.AddField(
            model_name='member',
            name='sa_passport_number',
            field=models.CharField(blank=True, help_text='South African passport number for citizens (for international travel)', max_length=25, null=True, verbose_name='SA Passport Number'),
        ),
    ]
