# Generated by Django 4.2.23 on 2025-07-11 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0028_remove_player_has_sa_passport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='registered_by_admin',
            field=models.BooleanField(default=False, help_text='Whether this member was registered by a club administrator', verbose_name='Registered by Admin'),
        ),
        migrations.AddField(
            model_name='member',
            name='registering_admin',
            field=models.ForeignKey(blank=True, help_text='The club administrator who registered this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
