# Generated by Django 4.2.23 on 2025-07-15 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0004_club_affiliation_fees_paid'),
        ('membership', '0031_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_members', to='geography.club'),
        ),
    ]
