# Generated by Django 4.2.23 on 2025-07-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0032_member_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='juniormember',
            name='birth_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='documents/birth_certificates/', verbose_name='Birth Certificate'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
    ]
