# Generated by Django 4.2.23 on 2025-07-17 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0004_club_affiliation_fees_paid'),
        ('membership', '0033_juniormember_birth_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_members', to='geography.association'),
        ),
    ]
