# Generated by Django 4.2.23 on 2025-07-19 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0004_club_affiliation_fees_paid'),
        ('membership', '0035_alter_member_member_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='association',
            field=models.ForeignKey(blank=True, help_text='Association this invoice is for (e.g., LFA, Region)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='geography.association'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='official',
            field=models.ForeignKey(blank=True, help_text='Official this invoice is for (if official registration)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_invoices', to='membership.official'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Player this invoice is for (if player registration)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_invoices', to='membership.member'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor associated with this invoice (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.vendor'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('JUNIOR', 'Junior Member (Under 18)'), ('SENIOR', 'Senior Member (18+)'), ('OFFICIAL', 'Club Official'), ('ADMIN', 'Administrator')], default='SENIOR', max_length=20, verbose_name='Member Type'),
        ),
    ]
