# Generated by Django 4.2.23 on 2025-07-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0036_invoice_association_invoice_official_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(blank=True, choices=[('JUNIOR', 'Junior Member (Under 18)'), ('SENIOR', 'Senior Member (18+)'), ('OFFICIAL', 'Club Official'), ('ADMIN', 'Administrator')], default='SENIOR', max_length=20, null=True, verbose_name='Member Type'),
        ),
    ]
