# Generated by Django 4.2.23 on 2025-07-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0004_club_affiliation_fees_paid'),
        ('membership', '0037_alter_member_member_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='national_federation',
            field=models.ForeignKey(default=1, help_text='The national federation this member belongs to', on_delete=django.db.models.deletion.PROTECT, to='geography.nationalfederation'),
        ),
    ]
