# Generated by Django 4.2.23 on 2025-07-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0038_member_national_federation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Membership Status'),
        ),
        migrations.AlterField(
            model_name='playerclubregistration',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('TRANSFERRED', 'Transferred')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
