# Generated by Django 4.2.23 on 2025-07-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0040_invoice_paid_amount_invoice_payment_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialcertification',
            name='official',
        ),
    ]
