# Generated by Django 5.2.3 on 2025-06-24 04:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(max_length=100, unique=True)),
                (
                    "device_info",
                    models.JSONField(
                        default=dict, help_text="Browser/device information"
                    ),
                ),
                ("offline_start", models.DateTimeField(auto_now_add=True)),
                ("offline_end", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("forms_filled", models.PositiveIntegerField(default=0)),
                ("pages_visited", models.PositiveIntegerField(default=0)),
                ("actions_queued", models.PositiveIntegerField(default=0)),
                ("sync_completed", models.BooleanField(default=False)),
                ("sync_errors", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-offline_start"],
            },
        ),
        migrations.CreateModel(
            name="PWAInstallation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("browser", models.CharField(max_length=50)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("DESKTOP", "Desktop"),
                            ("MOBILE", "Mobile"),
                            ("TABLET", "Tablet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "install_source",
                    models.CharField(
                        choices=[
                            ("BANNER", "Install Banner"),
                            ("MENU", "Browser Menu"),
                            ("MANUAL", "Manual Install"),
                        ],
                        max_length=50,
                    ),
                ),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("times_opened", models.PositiveIntegerField(default=0)),
                ("still_installed", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-installed_at"],
                "unique_together": {("user", "platform", "browser")},
            },
        ),
        migrations.CreateModel(
            name="SyncRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(help_text="Model being synced", max_length=100),
                ),
                (
                    "record_id",
                    models.CharField(
                        help_text="ID of the record being synced", max_length=100
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("CONFLICT", "Conflict"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(help_text="Data to be synced")),
                (
                    "conflict_data",
                    models.JSONField(
                        blank=True,
                        help_text="Server data in case of conflict",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "priority",
                    models.PositiveIntegerField(default=5, help_text="1=High, 5=Low"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="pwa_syncrec_user_id_228907_idx"
                    ),
                    models.Index(
                        fields=["model_name", "record_id"],
                        name="pwa_syncrec_model_n_b94693_idx",
                    ),
                    models.Index(
                        fields=["priority", "created_at"],
                        name="pwa_syncrec_priorit_c1162c_idx",
                    ),
                ],
            },
        ),
    ]
