# Generated by Django 5.2.3 on 2025-06-24 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pwa", "0001_initial"),
    ]

    operations = []
