# Generated by Django 5.2.1 on 2025-06-02 08:34

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("allowed_user_roles", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN_SYSTEM", "System Admin"),
                            ("ADMIN_COUNTRY", "Country Admin"),
                            ("ADMIN_FEDERATION", "Federation Admin"),
                            ("ADMIN_PROVINCE", "Province Admin"),
                            ("ADMIN_REGION", "Region Admin"),
                            ("ADMIN_LOCAL_FED", "Local Federation Admin"),
                            ("CLUB_ADMIN", "Club Administrator"),
                            ("PLAYER", "Player"),
                            ("REFEREE", "Referee"),
                            ("COACH", "Coach"),
                            ("EXECUTIVE", "Exco Member"),
                        ],
                        default="PLAYER",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("surname", models.CharField(blank=True, max_length=100)),
                ("alias", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        help_text="13-digit South African ID number",
                        max_length=20,
                    ),
                ),
                (
                    "id_number_other",
                    models.CharField(blank=True, max_length=25, null=True, unique=True),
                ),
                ("passport_number", models.CharField(blank=True, max_length=25)),
                (
                    "id_document_type",
                    models.CharField(
                        choices=[
                            ("BC", "Birth Certificate"),
                            ("PP", "Passport"),
                            ("ID", "National ID"),
                            ("DL", "Driver License"),
                            ("OT", "Other"),
                        ],
                        default="ID",
                        max_length=2,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("membership_card", models.BooleanField(default=False)),
                ("payment_required", models.BooleanField(default=True)),
                (
                    "safa_id",
                    models.CharField(blank=True, max_length=5, null=True, unique=True),
                ),
                (
                    "fifa_id",
                    models.CharField(blank=True, max_length=7, null=True, unique=True),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_photos/"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/%Y/%m/%d/"
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "registration_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.registrationtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("membership_type", models.CharField(max_length=50)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("postal_address", models.CharField(blank=True, max_length=255)),
                ("next_of_kin", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("payment_confirmed", models.BooleanField(default=False)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "player_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("JUN", "Junior"),
                            ("SEN", "Senior"),
                            ("VET", "Veteran"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "jersey_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("position", models.CharField(blank=True, max_length=50)),
                (
                    "association",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="association_memberships",
                        to="geography.association",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_memberships",
                        to="geography.club",
                    ),
                ),
                (
                    "local_football_association",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="geography.localfootballassociation",
                    ),
                ),
                (
                    "national_federation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="geography.nationalfederation",
                        verbose_name="National Federation",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="geography.region",
                        verbose_name="Region",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "user",
                            "membership_type",
                            "club",
                            "association",
                            "national_federation",
                        ),
                        name="unique_membership_combination",
                    )
                ],
            },
        ),
    ]
