# Generated by Django 4.2.23 on 2025-08-02 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lfaadministrator",
            name="lfa",
        ),
        migrations.RemoveField(
            model_name="lfaadministrator",
            name="user",
        ),
        migrations.RemoveConstraint(
            model_name="customuser",
            name="unique_id_number",
        ),
        migrations.RemoveConstraint(
            model_name="customuser",
            name="unique_passport_number",
        ),
        migrations.RemoveConstraint(
            model_name="customuser",
            name="unique_mother_body_when_not_blank",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="alias",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="birth_country",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="card_delivery_preference",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="club_membership_number",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="club_membership_verified",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="driver_license_number",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="employment_status",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="membership_card",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="membership_expires_date",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="membership_fee_amount",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="membership_paid_date",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="middle_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="organization_type",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="payment_required",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="physical_card_delivery_address",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="physical_card_requested",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="positions",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="profile_photo",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="registration_type",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="supporting_club",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="surname",
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="has_sa_passport",
            field=models.BooleanField(
                default=False, help_text="Does the user have a South African passport?"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the user's registration has been approved by an admin.",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sa_passport_document",
            field=models.FileField(
                blank=True,
                help_text="Scanned copy of SA Passport",
                null=True,
                upload_to="sa_passports/",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sa_passport_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sa_passport_number",
            field=models.CharField(
                blank=True,
                help_text="South African Passport Number",
                max_length=25,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="street_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="suburb",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="association",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geography.association",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geography.club",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country_code",
            field=models.CharField(default="ZAF", max_length=3),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="fifa_id",
            field=models.CharField(
                blank=True,
                help_text="Unique FIFA ID",
                max_length=7,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id_document",
            field=models.FileField(blank=True, null=True, upload_to="id_documents/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id_document_type",
            field=models.CharField(
                choices=[
                    ("BC", "Birth Certificate"),
                    ("PP", "Passport"),
                    ("ID", "National ID"),
                    ("DL", "Driver License"),
                    ("OT", "Other"),
                ],
                default="ID",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id_number",
            field=models.CharField(
                blank=True,
                help_text="South African ID Number",
                max_length=13,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id_number_other",
            field=models.CharField(
                blank=True,
                help_text="Other identification number",
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="local_federation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geography.localfootballassociation",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="membership_activated_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="membership_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("SUSPENDED", "Suspended"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mother_body",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geography.motherbody",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="national_federation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geography.nationalfederation",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="nationality",
            field=models.CharField(default="South African", max_length=50),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="passport_number",
            field=models.CharField(
                blank=True,
                help_text="Passport Number",
                max_length=25,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="popi_act_consent",
            field=models.BooleanField(default=False, help_text="Consent to POPI Act"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geography.province",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geography.region",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="registration_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="safa_id",
            field=models.CharField(
                blank=True,
                help_text="Unique SAFA ID",
                max_length=5,
                null=True,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="LFAAdministrator",
        ),
        migrations.DeleteModel(
            name="RegistrationType",
        ),
    ]
