# Generated by Django 5.2.1 on 2025-06-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN_FEDERATION", "Federation Admin"),
                    ("ADMIN_PROVINCE", "Province Admin"),
                    ("ADMIN_REGION", "Region Admin"),
                    ("ADMIN_LOCAL_FED", "Local Federation Admin"),
                    ("NATIONAL_ADMIN", "National Administrator"),
                    ("CLUB_ADMIN", "Club Administrator"),
                    ("PLAYER", "Player"),
                    ("REFEREE", "Referee"),
                    ("COACH", "Coach"),
                    ("EXECUTIVE", "Exco Member"),
                ],
                default="PLAYER",
                max_length=20,
            ),
        ),
    ]
