# Generated by Django 5.2.5 on 2025-08-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parental_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN_NATIONAL', 'National Federation Admin'), ('ADMIN_NATIONAL_ACCOUNTS', 'National Accounts Administrator'), ('ADMIN_PROVINCE', 'Provincial Administrator'), ('ADMIN_REGION', 'Regional Administrator'), ('ADMIN_LOCAL_FED', 'Local Federation Administrator'), ('CLUB_ADMIN', 'Club Administrator'), ('ASSOCIATION_ADMIN', 'Association Administrator')], default='MEMBER', max_length=30),
        ),
    ]
