# Generated by Django 4.2.16 on 2025-06-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="club_id",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="local_federation_id",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="province_id",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="region_id",
        ),
        migrations.AddField(
            model_name="customuser",
            name="card_delivery_preference",
            field=models.CharField(
                choices=[
                    ("DIGITAL_ONLY", "Digital Card Only"),
                    ("PHYSICAL_ONLY", "Physical Card Only"),
                    ("BOTH", "Both Digital and Physical"),
                ],
                default="DIGITAL_ONLY",
                help_text="Preferred card delivery method",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="membership_activated_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when membership was activated by admin",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="membership_expires_date",
            field=models.DateField(
                blank=True,
                help_text="Date when membership expires (annual renewal)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="membership_fee_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount paid for membership",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="membership_paid_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when membership payment was received",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="membership_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Payment"),
                    ("PAID", "Payment Received"),
                    ("ACTIVE", "Active Member"),
                    ("EXPIRED", "Membership Expired"),
                    ("SUSPENDED", "Membership Suspended"),
                ],
                default="PENDING",
                help_text="Current membership status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="physical_card_delivery_address",
            field=models.TextField(
                blank=True,
                help_text="Delivery address for physical card (if requested)",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="physical_card_requested",
            field=models.BooleanField(
                default=False, help_text="Whether user has requested a physical card"
            ),
        ),
    ]
