# Generated by Django 4.2.16 on 2025-06-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_club_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN_NATIONAL", "National Federation Admin"),
                    ("ADMIN_PROVINCE", "Province Admin"),
                    ("ADMIN_REGION", "Region Admin"),
                    ("ADMIN_LOCAL_FED", "Local Federation Admin"),
                    ("CLUB_ADMIN", "Club Administrator"),
                ],
                default="ADMIN_PROVINCE",
                max_length=20,
            ),
        ),
    ]
