# Generated by Django 5.2.2 on 2025-06-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="document",
        ),
        migrations.AddField(
            model_name="customuser",
            name="id_document",
            field=models.FileField(blank=True, null=True, upload_to="user_documents/"),
        ),
    ]
