# Generated by Django 5.2.5 on 2025-08-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_customuser_guardian_email_customuser_guardian_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("MEMBER", "Member"),
                    ("PLAYER", "Player"),
                    ("OFFICIAL", "Official"),
                    ("ADMIN_NATIONAL", "National Federation Admin"),
                    ("ADMIN_NATIONAL_ACCOUNTS", "National Accounts Administrator"),
                    ("ADMIN_PROVINCE", "Provincial Administrator"),
                    ("ADMIN_REGION", "Regional Administrator"),
                    ("ADMIN_LOCAL_FED", "Local Federation Administrator"),
                    ("CLUB_ADMIN", "Club Administrator"),
                    ("ASSOCIATION_ADMIN", "Association Administrator"),
                ],
                default="MEMBER",
                max_length=30,
            ),
        ),
    ]
