# Generated by Django 5.2.2 on 2025-06-07 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_document_field"),
        ("geography", "0002_alter_club_safa_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_users",
                to="geography.province",
            ),
        ),
    ]
