# Generated by Django 4.2.16 on 2025-06-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EMPLOYEE", "Full-time Employee"),
                    ("MEMBER", "Member (Political Structure)"),
                    ("PUBLIC", "Public/Supporter"),
                ],
                help_text="Employment/membership status within SAFA structure",
                max_length=20,
            ),
        ),
    ]
