# Generated by Django 5.2.2 on 2025-06-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_province"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="province",
        ),
        migrations.AddField(
            model_name="customuser",
            name="club_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country_code",
            field=models.CharField(blank=True, default="ZAF", max_length=3),
        ),
        migrations.AddField(
            model_name="customuser",
            name="local_federation_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="province_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="region_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id_number_other",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
