# Generated by Django 4.2.16 on 2025-06-10 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0002_club_fifa_id_club_payment_confirmed_and_more"),
        ("accounts", "0004_customuser_employment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="club_membership_number",
            field=models.CharField(
                blank=True,
                help_text="Club membership number for verification",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="club_membership_verified",
            field=models.BooleanField(
                default=False, help_text="Verified as bona fide club member"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="supporting_club",
            field=models.ForeignKey(
                blank=True,
                help_text="Club that this supporter follows",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supporters",
                to="geography.club",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN_NATIONAL", "National Federation Admin"),
                    ("ADMIN_PROVINCE", "Province Admin"),
                    ("ADMIN_REGION", "Region Admin"),
                    ("ADMIN_LOCAL_FED", "Local Federation Admin"),
                    ("CLUB_ADMIN", "Club Administrator"),
                    ("SUPPORTER", "Supporter/Public"),
                ],
                default="ADMIN_PROVINCE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("NATIONAL", "National Level"),
                            ("PROVINCE", "Province Level"),
                            ("REGION", "Region Level"),
                            ("LFA", "LFA Level"),
                            ("CLUB", "Club Level"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE", "Full-time Employee"),
                            ("MEMBER", "Member (Political Structure)"),
                            ("PUBLIC", "Public/Supporter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True, help_text="New positions need admin approval"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["level", "title"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="position",
            field=models.ForeignKey(
                blank=True,
                help_text="User's position within SAFA structure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.position",
            ),
        ),
    ]
