# Generated by Django 4.2.16 on 2025-06-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_club_membership_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id_number",
            field=models.CharField(
                blank=True,
                help_text="13-digit South African ID number",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="passport_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("passport_number__isnull", False),
                    models.Q(("passport_number", ""), _negated=True),
                ),
                fields=("passport_number",),
                name="unique_passport_number_when_not_blank",
            ),
        ),
    ]
