# Generated by Django 5.2.3 on 2025-06-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_refactor_positions"),
        ("accounts", "0005_alter_position_options_and_more"),
    ]

    operations = []
