# Generated by Django 5.2.2 on 2025-06-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_customuser_province_customuser_club_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="popi_act_consent",
            field=models.BooleanField(
                default=False,
                help_text="User must consent to POPI Act terms for registration",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN_PROVINCE", "Province Admin"),
                    ("ADMIN_REGION", "Region Admin"),
                    ("ADMIN_LOCAL_FED", "Local Federation Admin"),
                    ("CLUB_ADMIN", "Club Administrator"),
                ],
                default="ADMIN_PROVINCE",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Membership",
        ),
    ]
