# Generated by Django 5.2.3 on 2025-06-20 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_merge_20250620_2025"),
        ("geography", "0004_club_affiliation_fees_paid"),
    ]

    operations = [
        # Skip removing this constraint as it doesn't exist
        # migrations.RemoveConstraint(
        #    model_name="position",
        #    name="unique_title_per_level",
        # ),
        migrations.AddField(
            model_name="customuser",
            name="association",
            field=models.ForeignKey(
                blank=True,
                help_text="Association this user administers (required for association admins)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_users",
                to="geography.association",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN_NATIONAL", "National Federation Admin"),
                    ("ADMIN_PROVINCE", "Provincial Administrator"),
                    ("ADMIN_REGION", "Regionial Administrator"),
                    ("ADMIN_LOCAL_FED", "Local Federation Administrator"),
                    ("CLUB_ADMIN", "Club Administrator"),
                    ("ASSOCIATION_ADMIN", "Association Administrator"),
                ],
                default="ADMIN_PROVINCE",
                max_length=20,
            ),
        ),
    ]
