# Generated by Django 4.2.16 on 2025-06-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customuser_id_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id_document",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/user_documents/"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/profile_photos/"
            ),
        ),
    ]
