# Generated by Django 5.2.3 on 2025-06-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_position_unique_title_per_level_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="position",
            name="unique_title_per_level",
        ),
        migrations.AlterField(
            model_name="organizationtype",
            name="level",
            field=models.CharField(
                choices=[
                    ("NATIONAL", "National Federation"),
                    ("PROVINCE", "Province"),
                    ("REGION", "Region"),
                    ("LFA", "Local Football Association"),
                    ("ASSOCIATION", "Association"),
                    ("CLUB", "Club"),
                ],
                max_length=20,
            ),
        ),
    ]
