# Generated by Django 4.2.16 on 2025-06-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_customuser_id_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="driver_license_number",
            field=models.CharField(
                blank=True,
                help_text="Driver's license number",
                max_length=25,
                null=True,
            ),
        ),
    ]
