# Generated by Django 5.2.3 on 2025-06-21 06:41

from django.db import migrations

def create_referee_association_org_type(apps, schema_editor):
    """
    Create a default organization type for referee associations
    """
    OrganizationType = apps.get_model('accounts', 'OrganizationType')
    
    # First check if we already have an ASSOCIATION level org type
    association_type = OrganizationType.objects.filter(
        level='ASSOCIATION'
    ).first()
    
    # If not, create one
    if not association_type:
        association_type = OrganizationType.objects.create(
            name="Referee Association",
            level="ASSOCIATION",
            requires_approval=True,
            is_active=True
        )
        print(f"Created new organization type: {association_type}")

def reverse_func(apps, schema_editor):
    """
    Reverse function - we don't want to delete any data, so this is a no-op
    """
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_add_association_org_type"),
    ]

    operations = [
        migrations.RunPython(create_referee_association_org_type, reverse_func),
    ]
