# Generated by Django 4.2.16 on 2025-06-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_driver_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                fields=("title", "level"), name="unique_title_per_level"
            ),
        ),
    ]
