# Generated by Django 4.2.16 on 2025-06-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_position_title_position_unique_title_per_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="club_id",
            field=models.IntegerField(
                blank=True, help_text="Club ID for club admins", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="local_federation_id",
            field=models.IntegerField(
                blank=True, help_text="LFA ID for LFA admins", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="province_id",
            field=models.IntegerField(
                blank=True, help_text="Province ID for province admins", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="region_id",
            field=models.IntegerField(
                blank=True, help_text="Region ID for region admins", null=True
            ),
        ),
    ]
