# Generated by Django 5.2.3 on 2025-06-22 20:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_create_referee_association_org_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("player_id", "Player ID Document"),
                            ("player_passport", "Player Passport"),
                            ("player_sa_passport", "Player SA Passport"),
                            ("player_profile", "Player Profile Picture"),
                            ("official_id", "Official ID Document"),
                            ("official_passport", "Official Passport"),
                            ("official_cert", "Official Certification"),
                            ("club_document", "Club Document"),
                            ("other", "Other Document"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        help_text="Original document filename", max_length=255
                    ),
                ),
                (
                    "document_owner",
                    models.CharField(
                        help_text="Person/entity the document belongs to",
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("download", "Downloaded"),
                            ("print", "Printed"),
                        ],
                        default="view",
                        max_length=10,
                    ),
                ),
                (
                    "access_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "watermarked",
                    models.BooleanField(
                        default=False, help_text="Whether document was watermarked"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether access was successful"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the access"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who accessed the document",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Access Log",
                "verbose_name_plural": "Document Access Logs",
                "db_table": "document_access_log",
                "ordering": ["-access_time"],
            },
        ),
    ]
