# Generated by Django 4.2.23 on 2025-07-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_customuser_unique_id_number_when_not_blank_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email'], 'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='accounts_customuser',
        ),
    ]
