# Generated by Django 4.2.16 on 2025-06-12 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0002_club_fifa_id_club_payment_confirmed_and_more"),
        ("accounts", "0011_organizationtype_remove_customuser_club_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mother_body",
            field=models.ForeignKey(
                default=1,
                help_text="The national federation this user belongs to (defaults to SAFA)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="member_users",
                to="geography.nationalfederation",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="national_federation",
            field=models.ForeignKey(
                blank=True,
                help_text="National federation this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="federation_users",
                to="geography.nationalfederation",
            ),
        ),
    ]
