# Generated by Django 4.2.16 on 2025-06-12 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0002_club_fifa_id_club_payment_confirmed_and_more"),
        ("accounts", "0013_alter_customuser_mother_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="mother_body",
            field=models.ForeignKey(
                default=2,
                help_text="The national federation this user belongs to (defaults to SAFA)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="member_users",
                to="geography.nationalfederation",
            ),
        ),
    ]
