# Generated by Django 4.2.23 on 2025-07-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_mother_body_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_mother_body',
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('mother_body__isnull', False)), fields=('mother_body',), name='unique_mother_body_when_not_blank'),
        ),
    ]
