# Generated by Django 4.2.16 on 2025-06-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_customuser_mother_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="mother_body",
        ),
    ]
