# Generated by Django 4.2.23 on 2025-07-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_official'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Official',
        ),
    ]
