# Generated by Django 4.2.16 on 2025-06-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_customuser_mother_body"),
    ]

    operations = []
