# Generated by Django 4.2.16 on 2025-06-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_remove_mother_body_column"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="membership_fee_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount paid for membership in ZAR (South African Rand)",
                max_digits=10,
                null=True,
                verbose_name="Membership Fee (ZAR)",
            ),
        ),
    ]
