# Generated by Django 4.2.16 on 2025-06-13 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0004_set_default_registration_fees"),
        ("accounts", "0017_alter_customuser_membership_fee_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mother_body",
            field=models.ForeignKey(
                blank=True,
                help_text="The national federation this user belongs to (defaults to SAFA)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="member_users",
                to="geography.nationalfederation",
            ),
        ),
    ]
