# Generated by Django 4.2.16 on 2025-06-13 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0005_alter_province_name_motherbody"),
        ("accounts", "0018_customuser_mother_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="mother_body",
            field=models.ForeignKey(
                blank=True,
                help_text="The mother body this user belongs to (defaults to SAFAM)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="member_users",
                to="geography.motherbody",
            ),
        ),
    ]
