# Generated by Django 4.2.23 on 2025-07-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='position',
        ),
        migrations.AddField(
            model_name='customuser',
            name='positions',
            field=models.ManyToManyField(blank=True, help_text="User's positions within SAFA structure", to='accounts.position'),
        ),
    ]
