# Generated by Django 4.2.16 on 2025-06-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_customuser_mother_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_political_position",
        ),
    ]
