# Generated by Django 4.2.23 on 2025-07-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_customuser_position_customuser_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN_NATIONAL', 'National Federation Admin'), ('ADMIN_NATIONAL_ACCOUNTS', 'National Accounts Administrator'), ('ADMIN_PROVINCE', 'Provincial Administrator'), ('ADMIN_REGION', 'Regional Administrator'), ('ADMIN_LOCAL_FED', 'Local Federation Administrator'), ('CLUB_ADMIN', 'Club Administrator'), ('ASSOCIATION_ADMIN', 'Association Administrator')], default='ADMIN_PROVINCE', max_length=30),
        ),
    ]
