# Generated by Django 4.2.16 on 2025-06-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_remove_customuser_is_political_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN_NATIONAL", "National Federation Admin"),
                    ("ADMIN_PROVINCE", "Provincial Administrator"),
                    ("ADMIN_REGION", "Regionial Administrator"),
                    ("ADMIN_LOCAL_FED", "Local Federation Administrator"),
                    ("CLUB_ADMIN", "Club Administrator"),
                ],
                default="ADMIN_PROVINCE",
                max_length=20,
            ),
        ),
    ]
