# Generated by Django 4.2.16 on 2025-06-08 22:14

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "safa_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique 5-character SAFA identifier",
                        max_length=5,
                        unique=True,
                        verbose_name="SAFA ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "acronym",
                    models.CharField(blank=True, max_length=10, verbose_name="Acronym"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "headquarters",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Headquarters"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Association",
                "verbose_name_plural": "Associations",
                "ordering": ["national_federation", "name"],
            },
        ),
        migrations.CreateModel(
            name="Continent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "code",
                    models.CharField(blank=True, max_length=2, verbose_name="Code"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContinentRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "continent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="geography.continent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Continent Region",
                "verbose_name_plural": "Continent Regions",
                "ordering": ["continent", "name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="Country Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "continent_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="countries",
                        to="geography.continentregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "safa_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique SAFA identification",
                        max_length=20,
                        null=True,
                        verbose_name="SAFA ID",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geography.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
                "ordering": ["country", "name"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("allowed_user_roles", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WorldSportsBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "acronym",
                    models.CharField(blank=True, max_length=10, verbose_name="Acronym"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "headquarters",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Headquarters"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "sport_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SOCCER", "Soccer"),
                            ("RUGBY", "Rugby"),
                            ("CRICKET", "Cricket"),
                            ("BASKETBALL", "Basketball"),
                            ("HOCKEY", "Hockey"),
                            ("TENNIS", "Tennis"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Sport code for this world sports body",
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "World Sports Body",
                "verbose_name_plural": "World Sports Bodies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "safa_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique 5-character SAFA identifier",
                        max_length=5,
                        unique=True,
                        verbose_name="SAFA ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geography.province",
                    ),
                ),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "ordering": ["province", "name"],
            },
        ),
        migrations.CreateModel(
            name="NationalFederation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "safa_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique 5-character SAFA identifier",
                        max_length=5,
                        unique=True,
                        verbose_name="SAFA ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "acronym",
                    models.CharField(blank=True, max_length=10, verbose_name="Acronym"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "headquarters",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Headquarters"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geography.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "National Federation",
                "verbose_name_plural": "National Federations",
                "ordering": ["country", "name"],
            },
        ),
        migrations.CreateModel(
            name="LocalFootballAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "safa_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique 5-character SAFA identifier",
                        max_length=5,
                        unique=True,
                        verbose_name="SAFA ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "acronym",
                    models.CharField(blank=True, max_length=10, verbose_name="Acronym"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "headquarters",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Headquarters"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "association",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geography.association",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geography.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local Football Association",
                "verbose_name_plural": "Local Football Associations",
                "ordering": ["region", "name"],
            },
        ),
        migrations.AddField(
            model_name="continent",
            name="world_sports_body",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="continents",
                to="geography.worldsportsbody",
            ),
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Short code/abbreviation for the club",
                        max_length=10,
                        verbose_name="Club Code",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                            ("DISSOLVED", "Dissolved"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "founding_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Founding Date"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "stadium",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Stadium"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "colors",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Club Colors"
                    ),
                ),
                (
                    "safa_id",
                    models.CharField(
                        blank=True,
                        help_text="5-digit unique SAFA identification number",
                        max_length=5,
                        null=True,
                        unique=True,
                        verbose_name="SAFA ID",
                    ),
                ),
                (
                    "localfootballassociation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clubs",
                        to="geography.localfootballassociation",
                        verbose_name="Local Football Association",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clubs",
                        to="geography.province",
                        verbose_name="Province",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clubs",
                        to="geography.region",
                        verbose_name="Region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Club",
                "verbose_name_plural": "Clubs",
                "ordering": ["province", "region", "name"],
            },
        ),
        migrations.AddField(
            model_name="association",
            name="national_federation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geography.nationalfederation",
            ),
        ),
        migrations.CreateModel(
            name="ContinentFederation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100)),
                ("acronym", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "sport_code",
                    models.CharField(
                        choices=[
                            ("SOCCER", "Soccer"),
                            ("RUGBY", "Rugby"),
                            ("CRICKET", "Cricket"),
                            ("BASKETBALL", "Basketball"),
                            ("HOCKEY", "Hockey"),
                            ("TENNIS", "Tennis"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Sport code for this continental federation",
                        max_length=10,
                    ),
                ),
                (
                    "continent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="federations",
                        to="geography.continent",
                    ),
                ),
                (
                    "world_body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="continental_federations",
                        to="geography.worldsportsbody",
                    ),
                ),
            ],
            options={
                "verbose_name": "Continent Federation",
                "verbose_name_plural": "Continent Federations",
                "ordering": ["continent", "sport_code"],
                "unique_together": {("continent", "sport_code")},
            },
        ),
    ]
