# Generated by Django 5.2 on 2025-05-30 07:03

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Continent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("AF", "Africa"),
                            ("AS", "Asia"),
                            ("EU", "Europe"),
                            ("NA", "North America"),
                            ("OC", "Oceania"),
                            ("SA", "South America"),
                        ],
                        max_length=2,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("allowed_user_roles", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ContinentFederation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100)),
                ("acronym", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "sport_code",
                    models.CharField(
                        choices=[
                            ("SOCCER", "Soccer"),
                            ("RUGBY", "Rugby"),
                            ("CRICKET", "Cricket"),
                            ("BASKETBALL", "Basketball"),
                            ("HOCKEY", "Hockey"),
                            ("TENNIS", "Tennis"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Sport code for this continental federation",
                        max_length=10,
                    ),
                ),
                (
                    "continent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="federations",
                        to="geography.continent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Continent Federation",
                "verbose_name_plural": "Continent Federations",
                "ordering": ["continent", "sport_code"],
            },
        ),
        migrations.CreateModel(
            name="ContinentRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100)),
                ("acronym", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "continent_federation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regions",
                        to="geography.continentfederation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Continent Region",
                "verbose_name_plural": "Continent Regions",
                "ordering": ["continent_federation", "name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("fifa_code", models.CharField(max_length=3, unique=True)),
                (
                    "association_acronym",
                    models.CharField(default="SAFA", max_length=15),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "continent_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="countries",
                        to="geography.continentregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NationalFederation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100)),
                ("acronym", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="federations",
                        to="geography.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "National Federation",
                "verbose_name_plural": "National Federations",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=5)),
                (
                    "province_type",
                    models.CharField(
                        choices=[
                            ("INLAND", "Inland Province"),
                            ("COASTAL", "Coastal Province"),
                        ],
                        default="INLAND",
                        max_length=10,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provinces",
                        to="geography.country",
                    ),
                ),
            ],
            options={
                "unique_together": {("code", "country")},
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10)),
                (
                    "national_federation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regions",
                        to="geography.nationalfederation",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regions",
                        to="geography.province",
                    ),
                ),
            ],
            options={
                "unique_together": {("code", "province", "national_federation")},
            },
        ),
        migrations.CreateModel(
            name="LocalFootballAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100)),
                ("acronym", models.CharField(blank=True, max_length=10)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="geography.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local Football Association",
                "verbose_name_plural": "Local Football Associations",
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Short Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Club Code"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Founded Year"
                    ),
                ),
                (
                    "local_football_association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clubs",
                        to="geography.localfootballassociation",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clubs",
                        to="geography.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Club",
                "verbose_name_plural": "Clubs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorldSportsBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100)),
                ("acronym", models.CharField(max_length=10, unique=True)),
                (
                    "sport_code",
                    models.CharField(
                        choices=[
                            ("SOCCER", "Soccer"),
                            ("RUGBY", "Rugby"),
                            ("CRICKET", "Cricket"),
                            ("BASKETBALL", "Basketball"),
                            ("HOCKEY", "Hockey"),
                            ("TENNIS", "Tennis"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "continents",
                    models.ManyToManyField(
                        related_name="world_bodies", to="geography.continent"
                    ),
                ),
            ],
            options={
                "verbose_name": "World Sports Body",
                "verbose_name_plural": "World Sports Bodies",
                "ordering": ["sport_code", "name"],
            },
        ),
        migrations.AddField(
            model_name="nationalfederation",
            name="world_body",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="national_federations",
                to="geography.worldsportsbody",
            ),
        ),
        migrations.AddField(
            model_name="continentfederation",
            name="world_body",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="continental_federations",
                to="geography.worldsportsbody",
            ),
        ),
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100)),
                ("acronym", models.CharField(max_length=10)),
                ("association_type", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "national_federation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="associations",
                        to="geography.nationalfederation",
                    ),
                ),
            ],
            options={
                "unique_together": {("acronym", "national_federation")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="nationalfederation",
            unique_together={("country", "world_body")},
        ),
        migrations.AlterUniqueTogether(
            name="continentfederation",
            unique_together={("continent", "sport_code")},
        ),
    ]
