# Generated by Django 5.2.3 on 2025-06-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="safa_id",
            field=models.CharField(
                blank=True,
                help_text="Unique 5-character SAFA identifier",
                max_length=5,
                null=True,
                unique=True,
                verbose_name="SAFA ID",
            ),
        ),
        migrations.AlterField(
            model_name="localfootballassociation",
            name="safa_id",
            field=models.CharField(
                blank=True,
                help_text="Unique 5-character SAFA identifier",
                max_length=5,
                null=True,
                unique=True,
                verbose_name="SAFA ID",
            ),
        ),
        migrations.AlterField(
            model_name="nationalfederation",
            name="safa_id",
            field=models.CharField(
                blank=True,
                help_text="Unique 5-character SAFA identifier",
                max_length=5,
                null=True,
                unique=True,
                verbose_name="SAFA ID",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="safa_id",
            field=models.CharField(
                blank=True,
                help_text="Unique 5-character SAFA identifier",
                max_length=5,
                null=True,
                unique=True,
                verbose_name="SAFA ID",
            ),
        ),
    ]
