# Generated by Django 5.2.1 on 2025-06-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="safa_id",
            field=models.CharField(
                blank=True,
                help_text="Unique 5-character SAFA identifier",
                max_length=5,
                unique=True,
            ),
        ),
    ]
