# Generated by Django 5.2.5 on 2025-08-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrganizationLevel",
        ),
        migrations.DeleteModel(
            name="OrganizationType",
        ),
        migrations.AddField(
            model_name="association",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("SUSPENDED", "Suspended"),
                    ("DISSOLVED", "Dissolved"),
                ],
                default="INACTIVE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="localfootballassociation",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("SUSPENDED", "Suspended"),
                    ("DISSOLVED", "Dissolved"),
                ],
                default="INACTIVE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("SUSPENDED", "Suspended"),
                    ("DISSOLVED", "Dissolved"),
                ],
                default="INACTIVE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("SUSPENDED", "Suspended"),
                    ("DISSOLVED", "Dissolved"),
                ],
                default="INACTIVE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
