# Generated by Django 5.2 on 2025-05-18 18:43

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10)),
                ('association_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('home_ground', models.CharField(blank=True, max_length=100)),
                ('club_colors', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club_logos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('AF', 'Africa'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], max_length=2, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorldSportsBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10, unique=True)),
                ('sport_code', models.CharField(choices=[('SOCCER', 'Soccer'), ('RUGBY', 'Rugby'), ('CRICKET', 'Cricket'), ('BASKETBALL', 'Basketball'), ('HOCKEY', 'Hockey'), ('TENNIS', 'Tennis'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='world_bodies_logos/')),
            ],
            options={
                'verbose_name': 'World Sports Body',
                'verbose_name_plural': 'World Sports Bodies',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='country',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='country',
            name='association_acronym',
            field=models.CharField(default='SAFA', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='geography.country', verbose_name='Registered Country'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_number_other',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Admin'), ('ADMIN_COUNTRY', 'Country Admin'), ('PLAYER', 'Player'), ('CLUB', 'Club Manager'), ('REFEREE', 'Referee'), ('FED_ADMIN', 'Federation Admin'), ('PUBLIC', 'Public User'), ('COACH', 'Coach'), ('EXECUTIVE', 'Exco Member')], default='PLAYER', max_length=20),
        ),
        migrations.CreateModel(
            name='ContinentFederation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='continent_federation_logos/')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='federations', to='geography.continent')),
                ('world_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='continent_federations', to='geography.worldsportsbody')),
            ],
            options={
                'verbose_name': 'Continental Federation',
                'verbose_name_plural': 'Continental Federations',
                'unique_together': {('continent', 'world_body')},
            },
        ),
        migrations.CreateModel(
            name='ContinentRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='continent_region_logos/')),
                ('continent_federation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='geography.continentfederation')),
            ],
            options={
                'verbose_name': 'Continental Region',
                'verbose_name_plural': 'Continental Regions',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='continent_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='geography.continentregion'),
        ),
        migrations.CreateModel(
            name='NationalFederation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='national_federation_logos/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='federations', to='geography.country')),
                ('world_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='national_federations', to='geography.worldsportsbody')),
            ],
            options={
                'verbose_name': 'National Federation',
                'verbose_name_plural': 'National Federations',
                'unique_together': {('country', 'world_body')},
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('membership_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('player_category', models.CharField(blank=True, choices=[('JR', 'Junior (<18)'), ('SR', 'Senior (18+)'), ('SU', 'Supporter')], max_length=2, null=True)),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='geography.association')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='geography.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='geography.customuser')),
                ('national_federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='geography.nationalfederation')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
            },
        ),
        migrations.AddField(
            model_name='association',
            name='national_federation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associations', to='geography.nationalfederation'),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provinces', to='geography.country')),
            ],
            options={
                'unique_together': {('code', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('national_federation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='geography.nationalfederation')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='geography.province')),
            ],
            options={
                'unique_together': {('code', 'province', 'national_federation')},
            },
        ),
        migrations.AddField(
            model_name='club',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubs', to='geography.region'),
        ),
        migrations.AlterUniqueTogether(
            name='association',
            unique_together={('acronym', 'national_federation')},
        ),
    ]
