# Generated by Django 4.2.16 on 2025-06-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="fifa_id",
            field=models.CharField(
                blank=True,
                help_text="7-digit FIFA alphanumeric code (A-Z, 0-9)",
                max_length=7,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="payment_confirmed",
            field=models.BooleanField(
                default=False, help_text="Payment confirmed for SAFA registration"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="registration_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
