# Generated by Django 5.2.3 on 2025-06-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0002_alter_association_safa_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="club_documents",
            field=models.FileField(
                blank=True,
                help_text="Upload constitution or other compliance documents (PDF, DOC, etc)",
                null=True,
                upload_to="documents/club_documents/",
                verbose_name="Club Compliance Documents",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="club_owner_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIVATE", "Private"),
                    ("NPO", "NPO"),
                    ("CONSTITUTIONAL", "Constitutional"),
                ],
                help_text="Private, NPO, or Constitutional",
                max_length=20,
                null=True,
                verbose_name="Club Owner Type",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="club_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AMATEUR", "Amateur"),
                    ("SEMI_PROFESSIONAL", "Semi Professional"),
                    ("PROFESSIONAL", "Professional"),
                ],
                help_text="Amateur, Semi Professional, or Professional",
                max_length=20,
                null=True,
                verbose_name="Club Type",
            ),
        ),
    ]
