# Generated by Django 4.2.16 on 2025-06-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0002_club_fifa_id_club_payment_confirmed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="registration_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Registration fee amount in ZAR (South African Rand)",
                max_digits=10,
                verbose_name="Registration Fee",
            ),
        ),
    ]
