# Generated by Django 5.2.2 on 2025-06-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0002_alter_club_safa_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="safa_id",
            field=models.CharField(
                blank=True,
                help_text="5-digit unique SAFA identification number",
                max_length=5,
                null=True,
                unique=True,
                verbose_name="SAFA ID",
            ),
        ),
    ]
