# Generated by Django 5.2 on 2025-05-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_association_club_continent_worldsportsbody_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
