# Generated by Django 5.2 on 2025-05-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0002_add_headquarters_to_worldsportsbody"),
    ]

    operations = [
        migrations.AddField(
            model_name="worldsportsbody",
            name="sport_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOCCER", "Soccer"),
                    ("RUGBY", "Rugby"),
                    ("CRICKET", "Cricket"),
                    ("BASKETBALL", "Basketball"),
                    ("HOCKEY", "Hockey"),
                    ("TENNIS", "Tennis"),
                    ("OTHER", "Other"),
                ],
                help_text="Sport code for this world sports body",
                max_length=10,
                null=True,
            ),
        ),
    ]
