# Generated by Django 5.2.4 on 2025-08-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_delete_organizationlevel_delete_organizationtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='club_documents',
        ),
        migrations.AddField(
            model_name='association',
            name='compliance_verified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Compliance Verified Date'),
        ),
        migrations.AddField(
            model_name='association',
            name='constitution_document',
            field=models.FileField(blank=True, help_text="Upload the association's constitution (PDF, DOC, etc)", null=True, upload_to='documents/association_compliance/', verbose_name='Constitution Document'),
        ),
        migrations.AddField(
            model_name='association',
            name='fifa_id',
            field=models.CharField(blank=True, help_text='7-digit FIFA alphanumeric code (A-Z, 0-9)', max_length=7, null=True, unique=True, verbose_name='FIFA ID'),
        ),
        migrations.AddField(
            model_name='association',
            name='financial_statements_document',
            field=models.FileField(blank=True, help_text='Upload the latest financial statements', null=True, upload_to='documents/association_compliance/', verbose_name='Financial Statements'),
        ),
        migrations.AddField(
            model_name='association',
            name='is_compliant',
            field=models.BooleanField(default=False, help_text='Indicates if the association meets all compliance requirements', verbose_name='Compliance Verified'),
        ),
        migrations.AddField(
            model_name='association',
            name='minutes_of_agm_document',
            field=models.FileField(blank=True, help_text='Upload the minutes of the last Annual General Meeting', null=True, upload_to='documents/association_compliance/', verbose_name='Minutes of AGM'),
        ),
        migrations.AddField(
            model_name='club',
            name='compliance_verified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Compliance Verified Date'),
        ),
        migrations.AddField(
            model_name='club',
            name='constitution_document',
            field=models.FileField(blank=True, help_text="Upload the club's constitution (PDF, DOC, etc)", null=True, upload_to='documents/club_compliance/', verbose_name='Club Constitution'),
        ),
        migrations.AddField(
            model_name='club',
            name='financial_statements_document',
            field=models.FileField(blank=True, help_text='Upload the latest financial statements', null=True, upload_to='documents/club_compliance/', verbose_name='Financial Statements'),
        ),
        migrations.AddField(
            model_name='club',
            name='is_compliant',
            field=models.BooleanField(default=False, help_text='Indicates if the club meets all compliance requirements', verbose_name='Compliance Verified'),
        ),
        migrations.AddField(
            model_name='club',
            name='minutes_of_agm_document',
            field=models.FileField(blank=True, help_text='Upload the minutes of the last Annual General Meeting', null=True, upload_to='documents/club_compliance/', verbose_name='Minutes of AGM'),
        ),
        migrations.AddField(
            model_name='localfootballassociation',
            name='compliance_verified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Compliance Verified Date'),
        ),
        migrations.AddField(
            model_name='localfootballassociation',
            name='constitution_document',
            field=models.FileField(blank=True, help_text="Upload the LFA's constitution (PDF, DOC, etc)", null=True, upload_to='documents/lfa_compliance/', verbose_name='Constitution Document'),
        ),
        migrations.AddField(
            model_name='localfootballassociation',
            name='fifa_id',
            field=models.CharField(blank=True, help_text='7-digit FIFA alphanumeric code (A-Z, 0-9)', max_length=7, null=True, unique=True, verbose_name='FIFA ID'),
        ),
        migrations.AddField(
            model_name='localfootballassociation',
            name='financial_statements_document',
            field=models.FileField(blank=True, help_text='Upload the latest financial statements', null=True, upload_to='documents/lfa_compliance/', verbose_name='Financial Statements'),
        ),
        migrations.AddField(
            model_name='localfootballassociation',
            name='is_compliant',
            field=models.BooleanField(default=False, help_text='Indicates if the LFA meets all compliance requirements', verbose_name='Compliance Verified'),
        ),
        migrations.AddField(
            model_name='localfootballassociation',
            name='minutes_of_agm_document',
            field=models.FileField(blank=True, help_text='Upload the minutes of the last Annual General Meeting', null=True, upload_to='documents/lfa_compliance/', verbose_name='Minutes of AGM'),
        ),
        migrations.AddField(
            model_name='province',
            name='compliance_verified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Compliance Verified Date'),
        ),
        migrations.AddField(
            model_name='province',
            name='constitution_document',
            field=models.FileField(blank=True, help_text="Upload the province's constitution (PDF, DOC, etc)", null=True, upload_to='documents/province_compliance/', verbose_name='Constitution Document'),
        ),
        migrations.AddField(
            model_name='province',
            name='fifa_id',
            field=models.CharField(blank=True, help_text='7-digit FIFA alphanumeric code (A-Z, 0-9)', max_length=7, null=True, unique=True, verbose_name='FIFA ID'),
        ),
        migrations.AddField(
            model_name='province',
            name='financial_statements_document',
            field=models.FileField(blank=True, help_text='Upload the latest financial statements', null=True, upload_to='documents/province_compliance/', verbose_name='Financial Statements'),
        ),
        migrations.AddField(
            model_name='province',
            name='is_compliant',
            field=models.BooleanField(default=False, help_text='Indicates if the province meets all compliance requirements', verbose_name='Compliance Verified'),
        ),
        migrations.AddField(
            model_name='province',
            name='minutes_of_agm_document',
            field=models.FileField(blank=True, help_text='Upload the minutes of the last Annual General Meeting', null=True, upload_to='documents/province_compliance/', verbose_name='Minutes of AGM'),
        ),
        migrations.AddField(
            model_name='region',
            name='compliance_verified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Compliance Verified Date'),
        ),
        migrations.AddField(
            model_name='region',
            name='constitution_document',
            field=models.FileField(blank=True, help_text="Upload the region's constitution (PDF, DOC, etc)", null=True, upload_to='documents/region_compliance/', verbose_name='Constitution Document'),
        ),
        migrations.AddField(
            model_name='region',
            name='fifa_id',
            field=models.CharField(blank=True, help_text='7-digit FIFA alphanumeric code (A-Z, 0-9)', max_length=7, null=True, unique=True, verbose_name='FIFA ID'),
        ),
        migrations.AddField(
            model_name='region',
            name='financial_statements_document',
            field=models.FileField(blank=True, help_text='Upload the latest financial statements', null=True, upload_to='documents/region_compliance/', verbose_name='Financial Statements'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_compliant',
            field=models.BooleanField(default=False, help_text='Indicates if the region meets all compliance requirements', verbose_name='Compliance Verified'),
        ),
        migrations.AddField(
            model_name='region',
            name='minutes_of_agm_document',
            field=models.FileField(blank=True, help_text='Upload the minutes of the last Annual General Meeting', null=True, upload_to='documents/region_compliance/', verbose_name='Minutes of AGM'),
        ),
    ]
