# Generated by Django 4.2.16 on 2025-06-12 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0003_alter_club_registration_fee"),
    ]

    operations = [
        migrations.RunPython(
            # Forward migration: set default fees for clubs
            code=lambda apps, schema_editor: set_default_fees(apps, schema_editor),
            # Backward migration: do nothing
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]

def set_default_fees(apps, schema_editor):
    """
    Set default registration fees for clubs based on their tier if not already set.
    Default value is 1000 ZAR.
    """
    # Get the historical version of the Club model
    Club = apps.get_model("geography", "Club")
    
    # Set default fee of 1000 ZAR for all clubs that don't have a fee set
    # The model's default of 0.00 will already be applied for new clubs,
    # but we want to set it to a more realistic value for existing clubs
    from decimal import Decimal
    for club in Club.objects.filter(registration_fee=Decimal('0.00')):
        club.registration_fee = Decimal('1000.00')
        club.save(update_fields=['registration_fee'])
