# Generated by Django 5.2.1 on 2025-05-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0003_customuser_logo_alter_association_logo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="continentregion",
            options={
                "ordering": ["continent_federation", "name"],
                "verbose_name": "Continent Region",
                "verbose_name_plural": "Continent Regions",
            },
        ),
    ]
