# Generated by Django 5.2 on 2025-05-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0003_customuser_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="association_logos/"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="country_logos/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
        migrations.AddField(
            model_name="province",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="province_logos/"),
        ),
        migrations.AddField(
            model_name="region",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="region_logos/"),
        ),
    ]
