# Generated by Django 5.2.3 on 2025-06-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0003_club_club_documents_club_club_owner_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="affiliation_fees_paid",
            field=models.BooleanField(
                default=False,
                help_text="Has the club paid its affiliation fees for the season?",
                verbose_name="Affiliation Fees Paid",
            ),
        ),
    ]
