# Generated by Django 5.2 on 2025-05-30 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0003_worldsportsbody_sport_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="continentregion",
            options={
                "ordering": ["continent", "name"],
                "verbose_name": "Continent Region",
                "verbose_name_plural": "Continent Regions",
            },
        ),
        migrations.RemoveField(
            model_name="continentregion",
            name="acronym",
        ),
        migrations.RemoveField(
            model_name="continentregion",
            name="continent_federation",
        ),
        migrations.RemoveField(
            model_name="continentregion",
            name="website",
        ),
        migrations.AddField(
            model_name="continentregion",
            name="code",
            field=models.CharField(blank=True, max_length=10, verbose_name="Code"),
        ),
        migrations.AddField(
            model_name="continentregion",
            name="continent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="geography.continent",
            ),
        ),
        migrations.AlterField(
            model_name="continentregion",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="continentregion",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
    ]
