# Generated by Django 5.2 on 2025-05-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0004_add_code_to_continentregion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="continentregion",
            name="code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Code"
            ),
        ),
    ]
