# Generated by Django 5.2 on 2025-05-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0004_alter_continentregion_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="province",
            name="province_type",
            field=models.CharField(
                choices=[
                    ("INLAND", "Inland Province"),
                    ("COASTAL", "Coastal Province"),
                ],
                default="INLAND",
                max_length=10,
            ),
        ),
    ]
