# Generated by Django 4.2.16 on 2025-06-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0004_set_default_registration_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="province",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Name"
            ),
        ),
        migrations.CreateModel(
            name="MotherBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "country",
                    models.ForeignKey(
                        help_text="The country this mother body belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geography.country",
                    ),
                ),
            ],
        ),
    ]
