# Generated by Django 5.2 on 2025-05-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0005_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldsportsbody',
            name='continents',
            field=models.ManyToManyField(related_name='world_bodies', to='geography.continent'),
        ),
    ]
