# Generated by Django 5.2 on 2025-05-30 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0005_alter_continentregion_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="association_acronym",
        ),
        migrations.RemoveField(
            model_name="country",
            name="fifa_code",
        ),
        migrations.RemoveField(
            model_name="country",
            name="is_default",
        ),
        migrations.AddField(
            model_name="country",
            name="code",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Country Code"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="country",
            name="continent_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="countries",
                to="geography.continentregion",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
    ]
