# Generated by Django 5.2 on 2025-05-26 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0005_club_notes_province_province_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="province",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clubs",
                to="geography.province",
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="province_type",
            field=models.CharField(
                choices=[
                    ("INLAND", "Inland Province"),
                    ("COASTAL", "Coastal Province"),
                ],
                default="Inland",
                max_length=10,
            ),
        ),
    ]
