# Generated by Django 4.2.16 on 2025-06-15 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0005_alter_province_name_motherbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='continentregion',
            name='continent_federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='geography.continentfederation'),
        ),
    ]
