# Generated by Django 5.2 on 2025-05-27 03:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0006_club_province_alter_province_province_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clubs",
                to="geography.region",
            ),
        ),
        migrations.CreateModel(
            name="LocalFootballAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("name", models.CharField(max_length=100)),
                ("acronym", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="local_football_association",
                        to="geography.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local Football Association",
                "verbose_name_plural": "Local Football Associations",
            },
        ),
        migrations.AddField(
            model_name="club",
            name="local_football_association",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clubs",
                to="geography.localfootballassociation",
            ),
        ),
    ]
