# Generated by Django 5.2 on 2025-05-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0006_worldsportsbody_continents"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="fifa_id",
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="membership_card",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="payment_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="safa_id",
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
