# Generated by Django 5.2 on 2025-05-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0006_add_fields_to_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nationalfederation",
            options={
                "ordering": ["country", "name"],
                "verbose_name": "National Federation",
                "verbose_name_plural": "National Federations",
            },
        ),
        migrations.AlterUniqueTogether(
            name="nationalfederation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="nationalfederation",
            name="headquarters",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Headquarters"
            ),
        ),
        migrations.AlterField(
            model_name="nationalfederation",
            name="acronym",
            field=models.CharField(blank=True, max_length=10, verbose_name="Acronym"),
        ),
        migrations.AlterField(
            model_name="nationalfederation",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="geography.country"
            ),
        ),
        migrations.AlterField(
            model_name="nationalfederation",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="nationalfederation",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="nationalfederation",
            name="website",
            field=models.URLField(blank=True, verbose_name="Website"),
        ),
        migrations.RemoveField(
            model_name="nationalfederation",
            name="world_body",
        ),
    ]
