# Generated by Django 4.2.16 on 2025-06-15 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0006_continentregion_continent_federation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="province",
            options={
                "ordering": ["national_federation", "name"],
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
            },
        ),
        migrations.RemoveField(
            model_name="province",
            name="country",
        ),
        migrations.AddField(
            model_name="province",
            name="national_federation",
            field=models.ForeignKey(
                help_text="The national federation this province belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geography.nationalfederation",
            ),
        ),
    ]
