# Generated by Django 5.2 on 2025-05-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0007_alter_club_region_localfootballassociation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localfootballassociation",
            name="description",
        ),
        migrations.AlterField(
            model_name="localfootballassociation",
            name="acronym",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
