# Generated by Django 5.2 on 2025-05-30 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0007_add_headquarters_to_nationalfederation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="association",
            options={
                "ordering": ["national_federation", "name"],
                "verbose_name": "Association",
                "verbose_name_plural": "Associations",
            },
        ),
        migrations.AlterUniqueTogether(
            name="association",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="association",
            name="headquarters",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Headquarters"
            ),
        ),
        migrations.AddField(
            model_name="association",
            name="website",
            field=models.URLField(blank=True, verbose_name="Website"),
        ),
        migrations.AlterField(
            model_name="association",
            name="acronym",
            field=models.CharField(blank=True, max_length=10, verbose_name="Acronym"),
        ),
        migrations.AlterField(
            model_name="association",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="association",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="association",
            name="national_federation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geography.nationalfederation",
            ),
        ),
        migrations.RemoveField(
            model_name="association",
            name="association_type",
        ),
    ]
