# Generated by Django 5.2 on 2025-05-30 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0008_add_fields_to_association"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="province",
            options={
                "ordering": ["country", "name"],
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
            },
        ),
        migrations.AlterUniqueTogether(
            name="province",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="province",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="province",
            name="code",
            field=models.CharField(blank=True, max_length=10, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="province",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="geography.country"
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.RemoveField(
            model_name="province",
            name="province_type",
        ),
    ]
