# Generated by Django 5.2 on 2025-05-27 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0008_remove_localfootballassociation_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localfootballassociation",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="local_football_associations",
                to="geography.region",
            ),
        ),
    ]
