# Generated by Django 5.2 on 2025-05-30 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0009_add_description_to_province"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={
                "ordering": ["province", "name"],
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
            },
        ),
        migrations.AlterUniqueTogether(
            name="region",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="region",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="region",
            name="code",
            field=models.CharField(blank=True, max_length=10, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="region",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="geography.province"
            ),
        ),
        migrations.RemoveField(
            model_name="region",
            name="national_federation",
        ),
    ]
