# Generated by Django 5.2 on 2025-05-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0009_alter_localfootballassociation_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="short_name",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
