# Generated by Django 5.2 on 2025-05-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0010_alter_club_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="province",
            name="province_type",
            field=models.CharField(
                choices=[
                    ("INLAND", "Inland Province"),
                    ("COASTAL", "Coastal Province"),
                ],
                default="INLAND",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=(
                    "user",
                    "membership_type",
                    "club",
                    "association",
                    "national_federation",
                ),
                name="unique_membership_combination",
            ),
        ),
    ]
