# Generated by Django 5.2 on 2025-05-30 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0010_add_description_to_region"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="localfootballassociation",
            options={
                "ordering": ["region", "name"],
                "verbose_name": "Local Football Association",
                "verbose_name_plural": "Local Football Associations",
            },
        ),
        migrations.RemoveField(
            model_name="localfootballassociation",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="localfootballassociation",
            name="contact_phone",
        ),
        migrations.AddField(
            model_name="localfootballassociation",
            name="association",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geography.association",
            ),
        ),
        migrations.AddField(
            model_name="localfootballassociation",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="localfootballassociation",
            name="headquarters",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Headquarters"
            ),
        ),
        migrations.AlterField(
            model_name="localfootballassociation",
            name="acronym",
            field=models.CharField(blank=True, max_length=10, verbose_name="Acronym"),
        ),
        migrations.AlterField(
            model_name="localfootballassociation",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="localfootballassociation",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="geography.region"
            ),
        ),
        migrations.AlterField(
            model_name="localfootballassociation",
            name="website",
            field=models.URLField(blank=True, verbose_name="Website"),
        ),
    ]
