# Generated by Django 5.2 on 2025-05-28 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0011_alter_province_province_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="Region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="geography.region",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="membership",
            name="local_football_association",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="geography.localfootballassociation",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="next_of_kin",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="membership",
            name="postal_address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
