# Generated by Django 5.2 on 2025-05-31 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0011_add_fields_to_localfootballassociation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="club",
            options={
                "ordering": ["localfootballassociation", "name"],
                "verbose_name": "Club",
                "verbose_name_plural": "Clubs",
            },
        ),
        migrations.RemoveField(
            model_name="club",
            name="address",
        ),
        migrations.RemoveField(
            model_name="club",
            name="email",
        ),
        migrations.RemoveField(
            model_name="club",
            name="founded_year",
        ),
        migrations.RemoveField(
            model_name="club",
            name="local_football_association",
        ),
        migrations.RemoveField(
            model_name="club",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="club",
            name="region",
        ),
        migrations.RemoveField(
            model_name="club",
            name="short_name",
        ),
        migrations.AddField(
            model_name="club",
            name="colors",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Club Colors"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="club",
            name="founding_date",
            field=models.DateField(blank=True, null=True, verbose_name="Founding Date"),
        ),
        migrations.AddField(
            model_name="club",
            name="localfootballassociation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geography.localfootballassociation",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="stadium",
            field=models.CharField(blank=True, max_length=100, verbose_name="Stadium"),
        ),
        migrations.AddField(
            model_name="club",
            name="website",
            field=models.URLField(blank=True, verbose_name="Website"),
        ),
        migrations.AlterField(
            model_name="club",
            name="code",
            field=models.CharField(blank=True, max_length=10, verbose_name="Code"),
        ),
    ]
