# Generated by Django 5.2 on 2025-05-28 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0012_membership_region_membership_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="Region",
        ),
        migrations.AlterField(
            model_name="membership",
            name="national_federation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="geography.nationalfederation",
                verbose_name="National Federation",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="geography.region",
                verbose_name="Region",
            ),
        ),
    ]
