# Generated by Django 5.2 on 2025-06-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0012_add_fields_to_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="safa_id",
            field=models.CharField(
                blank=True,
                help_text="Unique 5-character SAFA identifier",
                max_length=5,
                unique=True,
                verbose_name="SAFA ID",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="safa_id",
            field=models.CharField(
                blank=True,
                help_text="Unique 5-character SAFA identifier",
                max_length=5,
                unique=True,
                verbose_name="SAFA ID",
            ),
        ),
        migrations.AddField(
            model_name="localfootballassociation",
            name="safa_id",
            field=models.CharField(
                blank=True,
                help_text="Unique 5-character SAFA identifier",
                max_length=5,
                unique=True,
                verbose_name="SAFA ID",
            ),
        ),
        migrations.AddField(
            model_name="nationalfederation",
            name="safa_id",
            field=models.CharField(
                blank=True,
                help_text="Unique 5-character SAFA identifier",
                max_length=5,
                unique=True,
                verbose_name="SAFA ID",
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="safa_id",
            field=models.CharField(
                blank=True,
                help_text="Unique 5-character SAFA identifier",
                max_length=5,
                unique=True,
                verbose_name="SAFA ID",
            ),
        ),
    ]
