# Generated by Django 5.2 on 2025-05-28 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0013_remove_membership_region_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localfootballassociation",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="geography.region"
            ),
        ),
    ]
