# Generated by Django 5.2 on 2025-05-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0014_alter_localfootballassociation_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="payment_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membership",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
