# Generated by Django 5.2 on 2025-06-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0015_fix_association_safa_id"),
    ]

    operations = []
