# Generated by Django 5.2 on 2025-06-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0013_add_nullable_safa_ids"),
        ("geography", "0016_add_nullable_safa_ids"),
    ]

    operations = []
