# Generated by Django 5.2 on 2025-06-01 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0017_merge_20250601_1615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="safa_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unique 5-character SAFA identifier",
                max_length=5,
                unique=True,
                verbose_name="SAFA ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="club",
            name="safa_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unique 5-character SAFA identifier",
                max_length=5,
                unique=True,
                verbose_name="SAFA ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="localfootballassociation",
            name="safa_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unique 5-character SAFA identifier",
                max_length=5,
                unique=True,
                verbose_name="SAFA ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nationalfederation",
            name="safa_id",
            field=models.CharField(
                blank=True,
                default=datetime.datetime(
                    2025, 6, 1, 17, 38, 4, 855269, tzinfo=datetime.timezone.utc
                ),
                help_text="Unique 5-character SAFA identifier",
                max_length=5,
                unique=True,
                verbose_name="SAFA ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="region",
            name="safa_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unique 5-character SAFA identifier",
                max_length=5,
                unique=True,
                verbose_name="SAFA ID",
            ),
            preserve_default=False,
        ),
    ]
