# Generated by Django 5.2 on 2025-06-01 19:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0018_alter_association_safa_id_alter_club_safa_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("SUSPENDED", "Suspended"),
                    ("DISBANDED", "Disbanded"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="code",
            field=models.CharField(
                blank=True,
                help_text='Short code/abbreviation for the club (e.g., "MFC" for "Metropolis Football Club")',
                max_length=10,
                verbose_name="Club Code",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="localfootballassociation",
            field=models.ForeignKey(
                default=datetime.datetime(
                    2025, 6, 1, 19, 2, 35, 250396, tzinfo=datetime.timezone.utc
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="geography.localfootballassociation",
                verbose_name="Local Football Association",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="club",
            index=models.Index(
                fields=["localfootballassociation", "name"],
                name="geography_c_localfo_d327d6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="club",
            index=models.Index(
                fields=["safa_id"], name="geography_c_safa_id_5966b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="club",
            index=models.Index(fields=["code"], name="geography_c_code_b0e85f_idx"),
        ),
    ]
