# Generated by Django 4.2.16 on 2025-06-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="season_year",
            field=models.CharField(help_text="e.g., 2025/2026", max_length=9),
        ),
    ]
