# Generated by Django 4.2.16 on 2025-06-09 20:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("league_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=200)),
                (
                    "jersey_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ]
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=20)),
                ("appearances", models.PositiveIntegerField(default=0)),
                ("goals", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("yellow_cards", models.PositiveIntegerField(default=0)),
                ("red_cards", models.PositiveIntegerField(default=0)),
                ("minutes_played", models.PositiveIntegerField(default=0)),
                ("clean_sheets", models.PositiveIntegerField(default=0)),
                ("saves", models.PositiveIntegerField(default=0)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="league_management.competition",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="league_management.competitionteam",
                    ),
                ),
            ],
            options={
                "ordering": ["-goals", "-assists", "player_name"],
                "unique_together": {("competition", "team", "player_name")},
            },
        ),
        migrations.CreateModel(
            name="LeagueTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("played", models.PositiveIntegerField(default=0)),
                ("won", models.PositiveIntegerField(default=0)),
                ("drawn", models.PositiveIntegerField(default=0)),
                ("lost", models.PositiveIntegerField(default=0)),
                ("goals_for", models.PositiveIntegerField(default=0)),
                ("goals_against", models.PositiveIntegerField(default=0)),
                ("goal_difference", models.IntegerField(default=0)),
                ("points", models.PositiveIntegerField(default=0)),
                ("form", models.CharField(blank=True, max_length=5)),
                ("home_wins", models.PositiveIntegerField(default=0)),
                ("away_wins", models.PositiveIntegerField(default=0)),
                ("clean_sheets", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_tables",
                        to="league_management.competition",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_tables",
                        to="league_management.competitiongroup",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="league_management.competitionteam",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("competition", "group", "team")},
            },
        ),
    ]
