# Generated by Django 4.2.16 on 2025-06-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league_management", "0002_playerstatistics_leaguetable"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_number",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="competition",
            name="safa_id",
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="safa_id",
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
