# Generated by Django 5.2.5 on 2025-09-04 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_verification', '0002_sportcode_tournamentcompetition_tournamentplayer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentregistration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournament_verification.tournamentcompetition'),
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
