# Generated by Django 5.2.4 on 2025-09-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_verification', '0003_alter_tournamentregistration_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
