# Generated by Django 5.2.4 on 2025-09-05 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_verification', '0004_alter_tournamentregistration_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team the player is registering for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournament_verification.tournamentteam'),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='team_logo',
            field=models.ImageField(blank=True, help_text='Team logo for visual selection', null=True, upload_to='tournament_teams/logos/'),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='team_photo',
            field=models.ImageField(blank=True, help_text='Team photo for visual selection', null=True, upload_to='tournament_teams/photos/'),
        ),
    ]
