# Generated by Django 5.2.4 on 2025-09-05 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_verification', '0005_tournamentregistration_team_tournamentteam_team_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentFixture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_date', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('pool', models.CharField(blank=True, help_text='Pool/Group name for pool play tournaments', max_length=10)),
                ('round_name', models.CharField(blank=True, help_text="Round name (e.g., 'Quarter Final', 'Semi Final')", max_length=50)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('home_score_et', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score_et', models.PositiveIntegerField(blank=True, null=True)),
                ('home_penalties', models.PositiveIntegerField(blank=True, null=True)),
                ('away_penalties', models.PositiveIntegerField(blank=True, null=True)),
                ('referee', models.CharField(blank=True, max_length=100)),
                ('assistant_referee_1', models.CharField(blank=True, max_length=100)),
                ('assistant_referee_2', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='tournament_verification.tournamentteam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='tournament_verification.tournamentteam')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='tournament_verification.tournamentcompetition')),
            ],
            options={
                'verbose_name': 'Tournament Fixture',
                'verbose_name_plural': 'Tournament Fixtures',
                'ordering': ['match_date', 'venue'],
                'unique_together': {('tournament', 'home_team', 'away_team', 'match_date')},
            },
        ),
    ]
